#!/usr/bin/env bash

set -euo pipefail
LOCALISH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

source "${LOCALISH}/setup/init.bash"

repo-git 'https://github.com/powerline/fonts.git'
repo-run 'fonts/install.sh'

# Install D2Coding for Hanguel
# TODO: Check macos
# https://github.com/powerline/fonts/blob/master/install.sh
stow --dir="${LOCALISH}" --target="$HOME/Library/Fonts" 'fonts'
fc-cache -f "$HOME/Library/Fonts"
