#!/usr/bin/env bash

set -euo pipefail
LOCALISH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

source "${LOCALISH}/setup/init.bash"

# TODO: Currently macOS only
# Use zsh shell
if command-exists 'zsh'; then
  # To use 'non-stand shells'
  echo "$(command-path 'zsh')" | sudo tee -a '/etc/shells'
  chsh -s "$(command-path 'zsh')"
fi
