#!/usr/bin/env bash

set -euo pipefail

LOCALISH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "${LOCALISH}/lib/core.bash"
source "${LOCALISH}/lib/git.bash"

git-clone-or-pull \
  'https://github.com/pyenv/pyenv.git' \
  "${LOCAL_REPOS}/.pyenv"
git-clone-or-pull \
  'https://github.com/pyenv/pyenv-virtualenv.git' \
  "${LOCAL_REPOS}/.pyenv/plugins/pyenv-virtualenv"

append-localrc "export PYENV_ROOT=\"${LOCAL_REPOS}/.pyenv\""
append-localrc 'export PATH="$PYENV_ROOT/bin:$PATH"'
append-localrc 'eval "$(pyenv init -)"            # should be placed at very last'
append-localrc 'eval "$(pyenv virtualenv-init -)" # should be placed at very last'
