#!/usr/bin/env bash

set -euo pipefail

ENVSH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "${ENVSH}/lib/git.sh"
source "${ENVSH}/lib/localrc.sh"

git-clone-or-pull \
  'https://github.com/pyenv/pyenv.git' \
  "$HOME/.pyenv"
git-clone-or-pull \
  'https://github.com/pyenv/pyenv-virtualenv.git' \
  "$HOME/.pyenv/plugins/pyenv-virtualenv"

append-localrc 'export PYENV_ROOT="$HOME/.pyenv"'
append-localrc 'export PATH="$PYENV_ROOT/bin:$PATH"'

append-localrc 'eval "$(pyenv init -)"            # should be placed at very last'
append-localrc 'eval "$(pyenv virtualenv-init -)" # should be placed at very last'
