#!/usr/bin/env bash
{
set -euo pipefail
eval "$(curl -sL locali.sh/init.bash)"

gitrepo 'https://github.com/pyenv/pyenv.git'
gitrepo 'https://github.com/pyenv/pyenv-virtualenv.git' 'pyenv/plugins'

localrc << EOF
export PYENV_ROOT="$(home_relpath "${LOCAL_REPO}/pyenv")"
export PATH="\${PYENV_ROOT}/bin:\${PATH}"
eval "\$(pyenv init -)"
eval "\$(pyenv virtualenv-init -)"
EOF
}
