#!/usr/bin/env bash

set -euo pipefail
LOCALISH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

source "${LOCALISH}/setup/init.bash"

repo-git 'https://github.com/robbyrussell/oh-my-zsh.git'

localrc-add 'oh-my-zsh' <<EOF
export ZSH="${LOCAL_REPO}/oh-my-zsh"
EOF

