#!/usr/bin/env python3

# -*- coding: utf-8 -*-

from io import BytesIO
import os
import re
import sys

import pycurl
import clipboard


def main():
    anki_media, word = params()

    filename = f'{word}.mp3'
    filepath = os.path.join(anki_media, filename)
    bytes_ = voice_of(word)

    save(filepath, bytes_)
    clip(filename)
    play(filepath)


def params():
    anki_media = os.getenv('ANKI_MEDIA', '.')
    if len(sys.argv) != 2:
        cmd = os.path.basename(sys.argv[0])
        errexit(f'Usage: {cmd} <word>')
    else:
        word = sys.argv[1]
        return anki_media, word


def voice_of(word):
    page_source = fetch_endic_naver(word)
    voice_url = extract_voice_url(page_source)
    return do_curl(voice_url)


def voice_of(word):
    url = 'http://endic.naver.com/search.nhn?sLn=en&query={}'.format(word)
    page_source = do_curl(url).decode('utf-8')

    mo = re.search(r'playlist="([^"]+)"', page_source)
    if mo:
        voice_url = mo.group(1)
        return do_curl(voice_url)
    else:
        errexit(f"Unable to find voice for '{word}'")


def do_curl(url):
    buf = BytesIO()
    c = pycurl.Curl()
    c.setopt(c.URL, url)
    c.setopt(c.WRITEDATA, buf)
    c.perform()
    c.close()
    return buf.getvalue()


def save(filepath, bytes_):
    with open(filepath, 'wb') as f:
        f.write(bytes_)


def clip(filename):
    clipboard.copy(f'[sound:{filename}]')


def play(filepath):
    cmd = '( afplay "{}" & )'.format(filepath)
    os.system(cmd)


def errexit(message):
    print(message, file=sys.stderr)
    sys.exit(1)


if __name__ == '__main__':
    main()
