#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from datetime import datetime
import os
import sys

import clipboard


def main():
    anki_media, srcpath, ss, to = params()
    srcname = os.path.basename(srcpath)

    now = datetime.now().strftime('%Y%m%d-%H%M%S')
    dstname = '%s.mp3' % now
    dstpath = os.path.join(anki_media, dstname)

    do_ffmpeg(srcpath, ss, to, dstpath)
    clip(dstname)
    play(dstpath)


def params():
    anki_media = os.getenv('ANKI_MEDIA', None)
    if anki_media is None:
        print("'ANKI_MEDIA' is not set. Use current working directory.")
        anki_media = '.'

    if len(sys.argv) != 4:
        cmd = os.path.basename(sys.argv[0])
        errexit('Usage: %s <srcpath> <ss> <to>' % cmd)

    srcpath, ss, to = sys.argv[1:]
    if not os.path.exists(srcpath):
        errexit("'%s' not exsisting" % srcpath)

    return anki_media, srcpath, ss, to


def do_ffmpeg(srcpath, ss, to, dstpath):
    cmd = ' '.join([
        'ffmpeg',
        '-y',                            # Overwrite output without asking
        '-loglevel 0',                   # Panic, only show fatal errors
        "-i '%s'" % srcpath,             # Input
        '-vn',                           # Disable video
        '-codec:a libmp3lame',           # Encode mp3
        '-qscale:a 3',                   # Just audible is enough
        "-ss '%s' -to '%s'" % (ss, to),  # Specify range
        "'%s'" % dstpath                 # Output
    ])
    os.system(cmd)


def clip(filename):
    anki_sound_field = '[sound:%s]' % filename
    clipboard.copy(anki_sound_field)
    print("Copied '%s' to clipboard" % anki_sound_field)


def play(dstpath):
    cmd = "(afplay '%s' &)" % dstpath
    os.system(cmd)


def errexit(message):
    print(message, file=sys.stderr)
    sys.exit(1)


if __name__ == '__main__':
    main()
