#!/usr/bin/env python3

import time

import pyperclip


HR = '-' * 100


def main():
    last = ''
    while True:
        current = pyperclip.paste()
        if current != last:
            replaced = replace(current)
            pyperclip.copy(replaced)
            print(HR)
            print(replaced)
            last = replaced
        time.sleep(1)


def replace(orig):
    r = orig
    r = r.strip()
    r = r.replace('. ', '.\n')
    return r


if __name__ == '__main__':
    main()
