#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

import glob
import os
import re
import tempfile
import sys

import click
from pydub import AudioSegment
import pyperclip
import speech_recognition


@click.command()
@click.option('--anki-media', envvar='ANKI_MEDIA')
def main(anki_media):
    fp = pick_filepath(anki_media)
    wfp = ensure_wav(fp)
    recognize(wfp)
    play(wfp)


def pick_filepath(anki_media):
    files = glob.glob(os.path.join(anki_media, '*.mp3'))
    latest = max(files, key=os.path.getctime)
    return latest


def ensure_wav(filepath):
    _, ext = os.path.splitext(filepath)
    if ext == '.mp3':
        mp3 = AudioSegment.from_mp3(filepath)
        _, wfp = tempfile.mkstemp()
        mp3.export(wfp, format='wav')
        return wfp
    elif ext == '.wav':
        return filepath
    else:
        sys.exit("invalid file extension: '%s'" % filepath)


def recognize(wav_filepath):
    r = speech_recognition.Recognizer()
    with speech_recognition.AudioFile(wav_filepath) as source:
        audio = r.record(source)
        text = r.recognize_google_cloud(audio)
        pyperclip.copy(text)
        print(text)


def play(dstpath):
    cmd = "afplay '%s'" % dstpath
    os.system(cmd)


if __name__ == '__main__':
    main()
