#!/usr/bin/env python3

import re
from signal import signal, SIGINT, SIGTSTP
import sys
import time

from pyperclip import copy, paste


HR = '-' * 80

LAST, WORKING = 0, 1

def main():
    cxt = ['', True]

    def quit(signum, frame):
        sys.exit()

    def toggle(signum, frame):
        cxt[LAST] = ''
        cxt[WORKING] = not cxt[WORKING]
        print('- Enabled' if cxt[WORKING] else '- Disabled')

    signal(SIGINT, quit)
    signal(SIGTSTP, toggle)

    while True:
        time.sleep(.3)
        last, working = cxt
        if not working:
            continue

        s = paste()
        if s != last:
            r = replace(s)
            copy(r)
            print(HR)
            print(r)
            cxt[LAST] = r

def replace(s):
    r = s
    r = re.sub(r'\{\{c\d::([^}]+)\}\}', r'\1', r)
    r = r.strip()
    r = r.replace('. ', '.\n')
    return r


if __name__ == '__main__':
    main()
