#!/usr/bin/env python3

import sys
import clipboard


def main():
    trie = {}
    for line in sys.stdin:
        for term in parse(line):
            add(trie, term)

    lines = [format_line(prefix, rest) for prefix, rest in traverse(trie)]
    content = '\n'.join(lines)

    clipboard.copy(content)
    print(content)


def parse(line):
    for term in line.split(','):
        t = term.strip()
        if t:
            yield t


def add(trie, term, n=0):
    if n >= len(term):
        trie[''] = term
        return

    c = term[n]
    if c in trie:
        node = trie[c]
        if node == term:
            return
        if is_leaf(node):
            trie[c] = {}
            add(trie[c], node, n+1)

        add(trie[c], term, n+1)
    else:
        trie[c] = term


def is_leaf(node):
    return isinstance(node, str)


def traverse(trie, pre=''):
    for c, node in trie.items():
        prefix = pre + c
        if is_leaf(node):
            rest = node[len(prefix):]
            yield prefix, rest
        else:
            yield from traverse(node, prefix)


def format_line(prefix, term):
    return '%s{{c1::%s}}' % (prefix, term)


if __name__ == '__main__':
    main()
