#!/usr/bin/env python3

import os
import re
import sys

import click


DIR = click.Path(exists=True, file_okay=False, dir_okay=True)


@click.command()
@click.option('--dir', 'dir_', default='.', type=DIR)
@click.argument('input_pattern')
@click.argument('output_pattern')
def main(dir_, input_pattern, output_pattern):
    inputs = list_inputs(dir_)
    renamer = compile_renamer(input_pattern, output_pattern)
    outputs = [renamer(p) for p in inputs]

    plans = [(ip, op) for ip, op in zip(inputs, outputs) if op is not None]
    plans = sorted(plans)

    if not plans:
        click.echo("No files in '%s'" % dir_)
        sys.exit(0)

    apply_(plans)


def list_inputs(dir_):
    inputs = []

    for e in os.listdir(dir_):
        p = os.path.join(dir_, e)
        if os.path.isfile(p):
            inputs.append(p)

    return inputs


def compile_renamer(input_pattern, output_pattern):
    ro = compile_input_pattern(input_pattern)
    fmt = compile_output_pattern(output_pattern)

    def f(input_):
        head, tail = os.path.split(input_)
        name, ext = os.path.splitext(tail)
        mo = ro.match(name)
        if mo is not None:
            d = {k: int(v) for k, v in mo.groupdict().items()}
            renamed = fmt.format(**d)
            return os.path.join(head, renamed + ext)
        else:
            return None

    return f


def compile_input_pattern(input_pattern):
    def repl(mo):
        x = mo.group(0)
        a = x[0]
        assert all(a == ch for ch in x)
        return r'(?P<_%s>%s)' % (a, '\d'*len(x))

    terms = input_pattern.split()
    patterns = [re.sub(r'(\d)\1*', repl, term) for term in terms]
    patterns = [r'^'] + patterns + [r'$']
    regex = r'.*'.join(patterns)
    return re.compile(regex)


def compile_output_pattern(output_pattern):
    def repl(mo):
        x = mo.group(0)
        a = x[0]
        assert all(a == ch for ch in x)
        return r'{_%s:0%dd}' % (a, len(x))

    return re.sub(r'(\d)\1*', repl, output_pattern)


def apply_(plans):
    iw = max(len(ip) for ip, _ in plans)
    ow = max(len(op) for _, op in plans)

    for ip, op in plans:
        click.secho('{:{width}}'.format(ip, width=iw), fg='red', nl=False)
        click.secho(' -> ', nl=False)
        click.secho('{:{width}}'.format(op, width=ow), fg='green')

    if click.confirm(' rename?'):
        for ip, op in plans:
            os.rename(ip, op)


if __name__ == '__main__':
    main()
