#!/usr/bin/env bash

echo -e "\n> Update 'locali'";        "${HOME}/locali/update.sh"
echo -e "\n> Update 'yeonghoey'";     "${HOME}/yeonghoey/update.sh"
echo -e "\n> Run Emacs as a background process"
emacs &
