#!/usr/bin/env python3

import os
import sys

import click
from pytube import YouTube


@click.command()
@click.option('--itag', default=22)
@click.argument('url')
@click.argument('name', default=None)
def main(itag, url, name):
    yt = YouTube(url)
    stream = yt.streams.get_by_itag(itag)
    stream.download(filename=name)


if __name__ == '__main__':
    main()
