#!/usr/bin/env python3

import os
import sys

import click
import pyperclip
from pytube import YouTube


@click.command()
@click.option('--itag', default=22)
@click.argument('url')
@click.argument('name', default=None, required=False)
def main(itag, url, name):
    yt = YouTube(url)

    atag = '<a href="%s">%s</a>' % (url, yt.title)
    pyperclip.copy(atag)
    click.echo('Copy: %s' % atag)

    stream = yt.streams.get_by_itag(itag)
    default_name, ext = os.path.splitext(stream.default_filename)
    name = name or default_name

    click.echo("Download: '%s%s'" % (name, ext))
    stream.download(filename=name)

    caption = yt.captions.get_by_language_code('en')
    if caption is not None:
        click.echo("Download: '%s.srt'" % name)
        with open('%s.srt' % name, 'w') as f:
            f.write(caption.generate_srt_captions())


if __name__ == '__main__':
    main()
