#!/usr/bin/env python3

import os
import sys

import click
from pytube import YouTube


@click.command()
@click.option('--itag', default=22)
@click.argument('url')
@click.argument('name', default=None, required=False)
def main(itag, url, name):
    yt = YouTube(url)

    stream = yt.streams.get_by_itag(itag)
    default_name, _ = os.path.splitext(stream.default_filename)
    name = name or default_name

    stream.download(filename=name)

    caption = yt.captions.get_by_language_code('en')
    if caption is not None:
        with open('%s.srt' % name, 'w') as f:
            f.write(caption.generate_srt_captions())

if __name__ == '__main__':
    main()
