#!/usr/bin/env bash

set -euo pipefail
LOCALISH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

source "${LOCALISH}/setup/init.bash"

gitrepo 'https://github.com/sstephenson/bats.git'

"${LOCAL_REPO}/bats/install.sh" "${LOCAL_ROOT}"
