#!/usr/bin/env bash

set -euo pipefail
LOCALISH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

source "${LOCALISH}/setup/init.bash"

git-repo 'https://github.com/Homebrew/brew.git'
bin-link "brew/bin/brew"
