#!/usr/bin/env bash

set -euo pipefail
LOCALISH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

source "${LOCALISH}/setup/init.bash"

# NOTE: './setup/dotfiles -D' to unlink
stow --dir="${LOCALISH}" --target="${HOME}" "$@" 'dotfiles'

repo-git 'https://github.com/tmux-plugins/tpm'
repo-sym 'tpm' "$HOME/.tmux/plugins/tpm"
repo-run 'tpm/bindings/install_plugins'
