#!/usr/bin/env bash

set -euo pipefail
LOCALISH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

source "${LOCALISH}/setup/init.bash"

# TODO: Support linux
require 'brew'
brew tap 'd12frosted/emacs-plus'
brew install 'emacs-plus'
