#!/usr/bin/env bash

set -euo pipefail
LOCALISH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

source "${LOCALISH}/setup/init.bash"

# TODO: Check macos
# https://github.com/powerline/fonts/blob/master/install.sh
stow --dir="${LOCALISH}" --target="$HOME/Library/Fonts" 'fonts'
fc-cache -f "$HOME/Library/Fonts"
