#!/usr/bin/env bash

set -euo pipefail
LOCALISH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

source "${LOCALISH}/setup/init.bash"

# Test whether git is availvable
# macOS will prompt to install git if not available
git --version

# Xcode command line developer tools
xcode-select --install || true
