#!/usr/bin/env bash

set -euo pipefail
LOCALISH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

source "${LOCALISH}/setup/init.bash"

repo-git 'https://github.com/pyenv/pyenv.git'
repo-git 'https://github.com/pyenv/pyenv-virtualenv.git' 'pyenv/plugins'

localrc-add 'pyenv' << EOF
export PYENV_ROOT="${LOCAL_REPO}/pyenv"
export PATH="\${PYENV_ROOT}/bin:\${PATH}"
eval "\$(pyenv init -)"
eval "\$(pyenv virtualenv-init -)"
EOF
