#!/usr/bin/env bash

set -euo pipefail

readonly LOCALISH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${LOCALISH}/setup/init.bash"

# ------------------------------------------------------------------------------

source "${LOCALISH}/recipes/brew.bash"
