#!/usr/bin/env bash

set -euo pipefail

main() {
  eval "$(curl -s locali.sh/r/init.bash)"
  git_repo 'https://github.com/Homebrew/brew.git'

  # Add bin/brew to LOCAL_BIN
  ln -fs "${LOCAL_REPO}/brew/bin/brew" "${LOCAL_BIN}/"
}

main
